const queryFilters = async (req, res, next) => {
  let { page, size, minLat, maxLat, minLng, maxLng, minPrice, maxPrice } =
    req.query;
  const where = {};
  if ((page && isNaN(page)) || (page && page > 10) || !page) page = 1;
  if ((size && isNaN(size)) || (size && size > 20) || !size) size = 20;
  console.log("SIZING ME UP:", size);
  page = parseInt(page);
  size = parseInt(size);
  console.log("SIZING ME UP:", size);
  next();
};
module.exports = queryFilters;

// {
//   "message": "Bad Request", // (or "Validation error" if generated by Sequelize),
//   "errors": {
//     "page": "Page must be greater than or equal to 1",
//     "size": "Size must be greater than or equal to 1",
//     "maxLat": "Maximum latitude is invalid",
//     "minLat": "Minimum latitude is invalid",
//     "minLng": "Maximum longitude is invalid",
//     "maxLng": "Minimum longitude is invalid",
//     "minPrice": "Minimum price must be greater than or equal to 0",
//     "maxPrice": "Maximum price must be greater than or equal to 0"
//   }
// }
